/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f446xx.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

class esc {
	private:
		TIM_TypeDef* timerhandle;
		float throttlepercentage;
	public:
		esc(TIM_TypeDef* timer) //inflexible design only on channel 1
		{
			timerhandle = timer;
			RCC -> AHB1ENR |= (1 << 0);
			RCC -> APB1ENR |= (1 << 1);
			GPIOA -> MODER &= ~(0b11 << 12);
			GPIOA -> MODER |= (0b10 << 12);
			GPIOA -> AFR[0] &= ~(0b1111 << 24);
			GPIOA -> AFR[0] |= (0b0010 << 24);
			timerhandle -> PSC = 0b1111;
			timerhandle -> ARR = 0b100111000011111;
			timerhandle -> CCMR1 |= (0b110 << 4);
			timerhandle -> CCMR1 |= (1 << 3);
			timerhandle -> CCER |= (1 << 0);
			timerhandle -> EGR |= (1 << 0);
			timerhandle ->CR1 |= (1 << 0);
		}
		void setThrottle(float percent)
		{
				float pulsewidthus;
				if(percent > 100)
				{
					percent = 100;
				}
				else if(percent < 0)
				{
					percent = 0;
				}
				pulsewidthus = 1000 + ((percent/100)*1000);
				timerhandle -> CCR1 = static_cast<uint32_t>(pulsewidthus);
				throttlepercentage = percent;
		}
};

class adc {
private:
	ADC_TypeDef* adchandle;
public:
	adc(ADC_TypeDef* AtoDC) // hardcoded to PA0 / ADC1 channel 0
	{
		adchandle = AtoDC;
		RCC -> AHB1ENR |= (1 << 0);
		RCC -> APB2ENR |= (1 << 8);
		GPIOA -> MODER &= ~(0b11 << 0);
		GPIOA -> MODER |= (0b11 << 0);
		adchandle -> SQR3 |= (0b0000 << 0);
		adchandle->SMPR2 |= (0b111 << 0);
		adchandle -> SQR1 |= (0b0000 << 20);
		adchandle -> CR2 |= (1 << 0);
	}
	uint32_t readRaw()
	{
	    adchandle->CR2 |= (1 << 30);        // SWSTART -- begin a conversion
	    while (!(adchandle->SR & (1 << 1))) { }   // poll EOC (End Of Conversion) flag until set
	    return adchandle->DR;               // read the result
	}
};

class PID {
private:
	float Kp;
	float Ki;
	float Kd;
	float P_term;
	float D_term;
	float I_term;
	float integral;
	float lasterror;
	float dt;
	float error;
	float derivative;
	float output;
public:
	PID(float P, float I, float D)
	{
		Kp = P;
		Ki = I;
		Kd = D;
		lasterror = 0;
		integral = 0;
		derivative = 0;
		output = 0;
	}
	float compute(float setpoint, float measured,float diff)
	{
		dt = diff;
		error = measured - setpoint;
		P_term = Kp * error;
		integral += error * dt;
		if (integral > 100.0f) { integral = 100.0f; }
		if (integral < -100.0f) { integral = -100.0f; }
		I_term = Ki * integral;
		derivative = (error - lasterror)/dt;
		if (derivative > 200.0f) { derivative = 200.0f; }
		if (derivative < -200.0f) { derivative = -200.0f; }
		D_term = Kd * derivative;
		lasterror = error;
		output = P_term + I_term + D_term;
		return output;
	}
};

volatile uint32_t msTicks = 0;

extern "C" void SysTick_Handler(void)
{
    msTicks++;
}

void initSysTick(void)
	{
	    SysTick->LOAD = 16000 - 1;      // 16,000,000 Hz clock / 1000 = 16,000 ticks per 1ms, minus 1 (counts from LOAD down to 0)
	    SysTick->VAL = 0;               // clear current count, start clean
	    SysTick->CTRL = (1 << 2) | (1 << 1) | (1 << 0);
	    // bit 2: CLKSOURCE = 1 -> use the processor clock directly (not an external/divided source)
	    // bit 1: TICKINT   = 1 -> enable the interrupt on each countdown-to-zero
	    // bit 0: ENABLE    = 1 -> start the counter
	}

int main(void)
{
	SCB->CPACR |= (0xF << 20);   // grant full access to the FPU coprocessor
	__DSB();                      // data synchronization barrier
	__ISB();                      // instruction synchronization barrier
	initSysTick();
	adc potadc(ADC1);
	esc motoresc(TIM3);
	PID pid(0.02,0.0003,0.01);
	volatile uint32_t i;
	uint32_t measure;
	float PIDout;
	for (i = 0; i < 2000000; i++) { }  // arming delay
	motoresc.setThrottle(0);
	for (i = 0; i < 2000000; i++) { }  // arming delay
	uint32_t lastTick = msTicks;
	while (1)
	    {
	        uint32_t currentTick = msTicks;
	        float dt = (currentTick - lastTick) / 1000.0f;   // elapsed time in seconds
	        lastTick = currentTick;
	        measure = potadc.readRaw();
	        if (measure < 500) { measure = 500; }
	        if (measure > 4000) { measure = 4000; }
	        if (dt > 0.0001f) {
	        	PIDout = pid.compute(2708, measure, dt);
	        	if (PIDout > 3.0f) { PIDout = 3.0f; }    // tighter cap going up
	        	if (PIDout < -5.0f) { PIDout = -5.0f; }  // looser cap going down
	        	float commandedThrottle = 82.0f + PIDout;
	        	motoresc.setThrottle(commandedThrottle);
	        }   // setThrottle's own clamp handles out-of-range safely
	        for (i = 0; i < 20000; i++) { }  // rough delay, tune the number by trial
	        // ... read ADC, call pid.compute(setpoint, measured, dt), call setThrottle() ...
	    }
	for(;;);
}
